package:
  name: asyncserial
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  #: .. versionchanged:: 0.2.3
  #:     Avoid egg-related issues (see https://github.com/conda-forge/ase-feedstock/issues/16#issue-283390260).
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - pyserial
    #: .. versionadded:: 0.2.1
    #:     Add support for Python 2.7.
    #: .. versionchanged:: 0.2.3
    #:     Remove Python 2.7 selector, since trollius is also available for
    #:     Python 3.  This allows this package to still be `noarch: python`.
    - trollius
  run:
    - python
    - pyserial
    #: .. versionadded:: 0.2.1
    #:     Add support for Python 2.7.
    #: .. versionchanged:: 0.2.3
    #:     Remove Python 2.7 selector, since trollius is also available for
    #:     Python 3.  This allows this package to still be `noarch: python`.
    - trollius

test:
  imports:
    - asyncserial

about:
  home: https://m-labs.hk
  license: BSD
  summary: 'asyncio support for pyserial'
