package:
  name: asyncserial
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py27_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python 2.7*
    - pyserial
    - trollius
  run:
    - python 2.7*
    - pyserial
    - trollius

test:
  imports:
    - asyncserial

about:
  home: https://m-labs.hk
  license: BSD
  summary: 'asyncio support for pyserial'
