package:
  name: asyncserial
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py35_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: python setup.py install

requirements:
  build:
    - python
    - pyserial
    #: .. versionadded:: X.X.X
    #:     Add support for Python 2.7.
    - trollius  # [py27]
  run:
    - python
    - pyserial
    #: .. versionadded:: X.X.X
    #:     Add support for Python 2.7.
    - trollius  # [py27]

test:
  imports:
    - asyncserial

about:
  home: https://m-labs.hk
  license: BSD
  summary: 'asyncio support for pyserial'
